[[block]]
block = "music"
buttons = ["play"]
interface_name_exclude = [".*chromium.*"]
dynamic_width = true
hide_when_empty = true
marquee_speed = 1
format = "{player}: {combo}"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
format = " {layout}"
interval = 0.25

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"


[[block]]
block = "time"
interval = 60
format = "%a %d %b %R"

[icons]
name = "awesome5"

[icons.overrides]
memory_mem = " "
cpu = " "

[theme]
name = "plain"

[theme.overrides]
separator = " #  "
separator_fg = "#a89984"
separator_bg = "#504945"
idle_fg = "#fbf1c7"
idle_bg = "#504945"
info_fg = "#fbf1c7"
info_bg = "#504945"
good_fg = "#fbf1c7"
good_bg = "#504945"
warning_fg = "#cc241d"
warning_bg = "#504945"
critical_fg = "#cc241d"
critical_bg = "#504945"
