icons = "awesome"

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "custom"
command = "xkblayout-state print %s"
interval = 0.25

[[block]]
block = "battery"
upower=true
format = "{percentage}% {time}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format_mem = "{Mug}GB/{MTg}GB({Mup}%)"
format_swap = "{SUg}GB/{STg}GB({SUp}%)"

[[block]]
block = "time"
interval = 60
format = "%a %d %b %R"

[theme]
name = "plain"

[theme.overrides]
separator_fg = "#a89984"
separator_bg = "#282828"
idle_fg = "#a89984"
idle_bg = "#282828"
info_fg = "#a89984"
info_bg = "#282828"
good_fg = "#a89984"
good_bg = "#282828"
warning_fg = "#cc241d"
warning_bg = "#282828"
critical_bg = "#282828"
