[[block]]
block = "sound"
step_width = 1

[[block]]
block = "custom"
command = "xkblayout-state print %s"
interval = 1

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"


[[block]]
block = "time"
interval = 60
format = "%a %d %b %R"

[icons]
name = "awesome5"

[icons.overrides]
memory_mem = " "
cpu = " "

[theme]
name = "gruvbox-light"

[icons]
name = "awesome5"

# [theme.overrides]
# separator_bg = "#fbf1c7"
# separator_fg = "#fbf1c7"
# idle_bg = "#fbf1c7"
# idle_fg = "#32302f"
# info_bg = "#fbf1c7"
# info_fg = "#32302f"
# good_bg = "#fbf1c7"
# good_fg = "#32302f"
# warning_fg = "#cc241d"
# warning_bg = "#fbf1c7"
# critical_fg = "#cc241d"
# critical_bg = "#32302f"
