icons = "awesome"

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "custom"
command = "xkblayout-state print %s"
interval = 0.25

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[bluetooth]]
block = "bluetooth"

[[block]]
block = "time"
interval = 60
format = "%a %d %b %R"

[theme]
name = "plain"

[theme.overrides]
separator_fg = "#282828"
separator_bg = "#282828"
idle_fg = "#fbf1c7"
idle_bg = "#282828"
info_fg = "#fbf1c7"
info_bg = "#282828"
good_fg = "#fbf1c7"
good_bg = "#282828"
warning_fg = "#cc241d"
warning_bg = "#282828"
critical_fg = "#cc241d"
critical_bg = "#282828"
